### ISSUE TITLE
脚本无响应

### ISSUE THREAD

**Issue by issaceyan** [hxlive/V2ray_ws_tls_With_Bt_Panel#3]
您好，脚本用不了呢。出现这些提示后就停了

2022-02-17 16:49:27 (21.2 MB/s) - 已保存 “tcp.sh” [24237/24237])

[root@1013285 ~]# wget -N --no-check-certificate "https://raw.githubusercontent.com/chiakge/Linux-NetSpeed/master/tcp.sh" && chmod +x tcp.sh ./tcp.sh
--2022-02-17 17:22:56--  https://raw.githubusercontent.com/chiakge/Linux-NetSpeed/master/tcp.sh
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：24237 (24K) [text/plain]
缺少“Last-modified”文件头 -- 关闭时间戳标记。
--2022-02-17 17:22:56--  https://raw.githubusercontent.com/chiakge/Linux-NetSpeed/master/tcp.sh
再次使用存在的到 raw.githubusercontent.com:443 的连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：24237 (24K) [text/plain]
正在保存至: “tcp.sh”

100%[====================================================================================================>] 24,237      --.-K/s 用时 0.007s  

2022-02-17 17:22:56 (3.29 MB/s) - 已保存 “tcp.sh” [24237/24237])

**Comment by hxlive** [comment]
这个脚本会替换系统内核文件，需要看系统版本。
另外，这个脚本的问题，建议与作者反馈一下。
